#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@tailscale[-1]
	add ucitrack tailscale
	set ucitrack.@tailscale[-1].init=tailscale
	commit ucitrack
EOF

/etc/init.d/tailscale enable
exit 0
