#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@tailscaler[-1]
	add ucitrack tailscaler
	set ucitrack.@tailscaler[-1].init=tailscaler
	commit ucitrack
EOF

/etc/init.d/tailscaler enable
exit 0
