#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95

get_config() {
	config_get_bool enabled $1 enabled 1
	config_get_bool acceptRoutes $1 acceptRoutes 0
	config_get loginServer $1 loginServer ""
	config_get authkey $1 authkey ""
	config_get hostname $1 hostname ""
	config_get advertiseRoutes $1 advertiseRoutes ""
}

start_service() {
	logger -t tailscaler 'start_service'
	config_load tailscaler
	config_foreach get_config settings
	procd_open_instance
	if [ $enabled != 1 ]; then
		procd_set_param command /etc/init.d/tailscaler stop
		procd_set_param stderr 1
		procd_set_param respawn
		procd_close_instance
		return 1
	fi
	# 
	procd_set_param command /usr/sbin/tailscale
	procd_append_param command up
	if [ $loginServer != "" ]; then
		procd_append_param command --login-server="$loginServer" 
	fi
	if [ $authkey != "" ]; then
		procd_append_param command --authkey "$authkey" 
	fi
	if [ $hostname != "" ]; then
		procd_append_param command --hostname="$hostname" 
	fi
	if [ $acceptRoutes == 1 ]; then
		procd_append_param command --accept-routes=true
	fi
	if [ $advertiseRoutes != "" ];then
		procd_append_param command --advertise-routes="$advertiseRoutes"
	fi
	procd_append_param command --reset
	procd_set_param respawn
	procd_set_param stdout 0
	procd_set_param stderr 1
	procd_close_instance
}

stop_service(){
	# /etc/init.d/tailscale stop
   	/usr/sbin/tailscaled --cleanup
}


service_triggers() {
	procd_add_reload_trigger "tailscaler"
}