#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

get_config() {
	config_get_bool enabled $1 enabled 1
	config_get_bool acceptRoutes $1 acceptRoutes 0
	config_get loginServer $1 loginServer
	config_get authkey $1 authkey
	config_get hostname $1 hostname
	config_get advertiseRoutes $1 advertiseRoutes
}

start_service() {
	config_load tailscaler
	config_foreach get_config tailscaler
	procd_open_instance
	if [ $enabled != 1 ]; then
		procd_set_param command /etc/init.d/tailscaler stop
		procd_set_param stderr 1
		procd_set_param respawn
		procd_close_instance
		return 1
	fi
	params=""
	if [ $loginServer != "" ]; then
		params="$params --login-server=$loginServer" 
	fi
	if [ $authkey != "" ]; then
		params="$params --authkey $authkey" 
	fi
	if [ $hostname != "" ]; then
		params="$params --hostname=$hostname" 
	fi
	if [ $acceptRoutes == 1 ]; then
		params="$params --accept-routes=true" 
	fi
	if [ $advertiseRoutes != "" ];then
		params="$params --advertise-routes=$advertiseRoutes"
	fi
	procd_set_param command tailscale up $params --reset > /tmp/tailscaler.log 2>&1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance
}

stop_service(){
    /usr/sbin/tailscaled --cleanup
}


service_triggers() {
	procd_add_reload_trigger "tailscaler"
}